# Generated by Django 5.0.6 on 2024-07-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_desciption_recipe_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_images/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
