# Generated by Django 5.0.6 on 2024-07-09 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_image_recipe_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="categories",
        ),
    ]
