# Generated by Django 5.0.6 on 2024-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipe_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(to="recipes.category"),
        ),
    ]
